# docker-compose syntax version
version: "3.9"

services:
  app:
    build:
      # uses the current directory we run the docker-compose from
      # working direcory for the following commands and for building
      # by default it will use the found Dockerfile for building
      context: .
      args:
        # development mode - see Dockerfile
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    # the default command to run - overwrites the CMD in Dockerfiles
    # can be overwwritten by a command given as arg for docker-compose run
    # ">" allows to specify one command in multi line format
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - db

  # second service: DB PostgreSQL
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/log/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

# named volumes
volumes:
  # if we do not specify the local folder after : then
  # it will be stored in the default folder for volumes
  dev-db-data:
  dev-static-data: